use super::*;

const CANDIDATE_MASK: u32 = 0x0300_0000;

fn candidate() -> FwmarkCandidate {
    FwmarkCandidate::new(CANDIDATE_MASK, 0x0100_0000, 0x0200_0000).unwrap()
}

fn fixture(family: NetworkAddressFamily, input_ordinal_padding: &str) -> String {
    let address = match family {
        NetworkAddressFamily::Ipv4 => "0.0.0.0/0",
        NetworkAddressFamily::Ipv6 => "::/0",
    };
    format!(
        "# Generated by iptables-save\n\
         *filter\n\
         :INPUT ACCEPT [17:4096]\n\
         -A INPUT -d {address} -j ACCEPT\n\
         COMMIT\n\
         *mangle\n\
         :INPUT ACCEPT [1:2]\n\
         :OUTPUT ACCEPT [3:4]\n\
         :POSTROUTING ACCEPT [5:6]\n\
         :routectrl_mangle_INPUT - [0:0]\n\
         :vendor_mangle_POSTROUTING - [0:0]\n\
         {input_ordinal_padding}\
         -A INPUT -j routectrl_mangle_INPUT\n\
         -A POSTROUTING -o wlan0 -j vendor_mangle_POSTROUTING\n\
         -A routectrl_mangle_INPUT -i rmnet_data0 -j MARK --set-xmark 0x64/0x7fefffff\n\
         -A routectrl_mangle_INPUT -i wlan0 -j MARK --set-xmark 0x65/0x7fefffff\n\
         -A vendor_mangle_POSTROUTING -o wlan0 -j MARK --set-xmark 0x0/0xffffffff\n\
         -A OUTPUT -m mark --mark 0x100/0xffff -j ACCEPT\n\
         -A OUTPUT -j CONNMARK --save-mark --nfmask 0xffff --ctmask 0xffff\n\
         COMMIT\n"
    )
}

#[test]
fn complete_dual_stack_projection_separates_sources_and_qualifies_exact_writes() {
    let observation = observe_android_xtables_fwmarks(
        fixture(NetworkAddressFamily::Ipv4, "").as_bytes(),
        fixture(NetworkAddressFamily::Ipv6, "").as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .expect("complete exact snapshots");

    assert_eq!(observation.table_count(), 4);
    assert_eq!(observation.chain_count(), 12);
    assert_eq!(observation.rule_count(), 16);
    assert_eq!(observation.flux_owned_chain_count(), 0);
    assert_eq!(
        observation.legacy_mark_uses(),
        [
            FwmarkUseRecord::new(
                FwmarkEvidenceSource::LegacyXtables,
                FwmarkPlane::Packet,
                FwmarkUseOperation::PredicateRead,
                0xffff,
            )
            .unwrap(),
            FwmarkUseRecord::new(
                FwmarkEvidenceSource::LegacyXtables,
                FwmarkPlane::Packet,
                FwmarkUseOperation::MaskedWrite,
                u32::MAX,
            )
            .unwrap(),
        ]
    );
    assert_eq!(observation.transfer_mark_uses().len(), 2);
    assert_eq!(observation.ordered_late_writes().len(), 6);
    assert_eq!(
        observation
            .ordered_late_writes()
            .iter()
            .filter(|record| record.hook() == FwmarkNetfilterBuiltinHook::Input)
            .count(),
        4
    );
    assert_eq!(
        observation
            .ordered_late_writes()
            .iter()
            .filter(|record| record.hook() == FwmarkNetfilterBuiltinHook::Postrouting)
            .count(),
        2
    );
}

#[test]
fn canonical_digest_ignores_comments_and_counters_but_binds_rule_order() {
    let first_v4 = fixture(NetworkAddressFamily::Ipv4, "");
    let first_v6 = fixture(NetworkAddressFamily::Ipv6, "");
    let second_v4 = first_v4
        .replace("# Generated by iptables-save", "# another volatile header")
        .replace("[17:4096]", "[999:888]")
        .replace("[1:2]", "[7:8]");
    let second_v6 = first_v6
        .replace("# Generated by iptables-save", "# another volatile header")
        .replace("[17:4096]", "[777:666]")
        .replace("[3:4]", "[11:12]");
    let first = observe_android_xtables_fwmarks(
        first_v4.as_bytes(),
        first_v6.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    let second = observe_android_xtables_fwmarks(
        second_v4.as_bytes(),
        second_v6.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    assert_eq!(first, second);

    let reordered_v4 = first_v4.replace(
        "-A INPUT -j routectrl_mangle_INPUT\n",
        "-A INPUT -j ACCEPT\n-A INPUT -j routectrl_mangle_INPUT\n",
    );
    let reordered = observe_android_xtables_fwmarks(
        reordered_v4.as_bytes(),
        first_v6.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    assert_ne!(first.digest(), reordered.digest());
    let ipv4_input_digest = |observation: &AndroidXtablesFwmarkObservation| {
        observation
            .ordered_late_writes()
            .iter()
            .find(|record| {
                record.family() == NetworkAddressFamily::Ipv4
                    && record.hook() == FwmarkNetfilterBuiltinHook::Input
            })
            .expect("IPv4 INPUT qualification")
            .selector_digest()
    };
    assert_ne!(ipv4_input_digest(&first), ipv4_input_digest(&reordered));
}

#[test]
fn candidate_overlapping_transfer_prevents_lifetime_qualification() {
    let ipv4 = fixture(NetworkAddressFamily::Ipv4, "").replace(
        "--nfmask 0xffff --ctmask 0xffff",
        "--nfmask 0xffffffff --ctmask 0xffffffff",
    );
    let observation = observe_android_xtables_fwmarks(
        ipv4.as_bytes(),
        fixture(NetworkAddressFamily::Ipv6, "").as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    assert!(
        observation
            .ordered_late_writes()
            .iter()
            .all(|record| { record.family() != NetworkAddressFamily::Ipv4 })
    );
    assert_eq!(
        observation
            .ordered_late_writes()
            .iter()
            .filter(|record| record.family() == NetworkAddressFamily::Ipv6)
            .count(),
        3
    );
}

#[test]
fn one_unqualified_duplicate_mask_keeps_the_whole_mark_use_unqualified() {
    let ipv4 = fixture(NetworkAddressFamily::Ipv4, "").replace(
        "-A OUTPUT -m mark",
        "-A OUTPUT -j MARK --set-xmark 0x0/0xffffffff\n-A OUTPUT -m mark",
    );
    let observation = observe_android_xtables_fwmarks(
        ipv4.as_bytes(),
        fixture(NetworkAddressFamily::Ipv6, "").as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    assert_eq!(
        observation
            .ordered_late_writes()
            .iter()
            .filter(|record| {
                record.family() == NetworkAddressFamily::Ipv4
                    && record.hook() == FwmarkNetfilterBuiltinHook::Postrouting
            })
            .count(),
        0
    );
}

#[test]
fn unknown_or_malformed_mark_semantics_fail_closed() {
    let base = fixture(NetworkAddressFamily::Ipv4, "");
    for changed in [
        base.replace(
            "-A OUTPUT -m mark --mark 0x100/0xffff -j ACCEPT",
            "-A OUTPUT --mark 0x100/0xffff -j ACCEPT",
        ),
        base.replace(
            "-A OUTPUT -m mark --mark 0x100/0xffff -j ACCEPT",
            "-A OUTPUT -j UNKNOWN --set-mark 0x1/0xff",
        ),
    ] {
        assert!(
            observe_android_xtables_fwmarks(
                changed.as_bytes(),
                fixture(NetworkAddressFamily::Ipv6, "").as_bytes(),
                AndroidNetdSourceProfile::AospNetd20250324,
                candidate(),
            )
            .is_err()
        );
    }
}

#[test]
fn wrong_incoming_profile_or_dynamic_selector_is_rejected() {
    let ipv4 = fixture(NetworkAddressFamily::Ipv4, "");
    assert_eq!(
        observe_android_xtables_fwmarks(
            ipv4.as_bytes(),
            fixture(NetworkAddressFamily::Ipv6, "").as_bytes(),
            AndroidNetdSourceProfile::AospAndroid13R1,
            candidate(),
        )
        .unwrap_err()
        .kind(),
        AndroidXtablesFwmarkObservationErrorKind::InvalidAndroidIncomingWriter
    );
    let wildcard = ipv4.replace("-i wlan0", "-i wlan+");
    assert_eq!(
        observe_android_xtables_fwmarks(
            wildcard.as_bytes(),
            fixture(NetworkAddressFamily::Ipv6, "").as_bytes(),
            AndroidNetdSourceProfile::AospNetd20250324,
            candidate(),
        )
        .unwrap_err()
        .kind(),
        AndroidXtablesFwmarkObservationErrorKind::InvalidAndroidIncomingWriter
    );
}

#[test]
fn parser_rejects_unbounded_or_ambiguous_documents() {
    let ipv6 = fixture(NetworkAddressFamily::Ipv6, "");
    for (input, expected) in [
        ("", AndroidXtablesFwmarkObservationErrorKind::EmptyInput),
        (
            "*mangle\n:INPUT ACCEPT [0:0]\nCOMMIT",
            AndroidXtablesFwmarkObservationErrorKind::MissingFinalLineFeed,
        ),
        (
            "*mangle\n:INPUT ACCEPT [0:0]\n-A INPUT -m comment --comment \"unterminated\nCOMMIT\n",
            AndroidXtablesFwmarkObservationErrorKind::InvalidQuotedToken,
        ),
        (
            "*mangle\n:INPUT ACCEPT [0:0]\n-A OUTPUT -j ACCEPT\nCOMMIT\n",
            AndroidXtablesFwmarkObservationErrorKind::UndeclaredRuleSource,
        ),
    ] {
        assert_eq!(
            observe_android_xtables_fwmarks(
                input.as_bytes(),
                ipv6.as_bytes(),
                AndroidNetdSourceProfile::AospNetd20250324,
                candidate(),
            )
            .unwrap_err()
            .kind(),
            expected
        );
    }
}

#[test]
fn mutation_forms_project_the_bits_they_can_change() {
    let base = "*mangle\n:OUTPUT ACCEPT [0:0]\n{}COMMIT\n";
    for (rule, mask) in [
        ("-A OUTPUT -j MARK --set-mark 0x12/0xff\n", 0xff),
        ("-A OUTPUT -j MARK --and-mark 0xffffff00\n", 0xff),
        ("-A OUTPUT -j MARK --or-mark 0x300\n", 0x300),
        ("-A OUTPUT -j MARK --xor-mark 0xc00\n", 0xc00),
        ("-A OUTPUT -j MARK --set-xmark 0x300/0xff\n", 0x3ff),
        ("-A OUTPUT -j TPROXY --tproxy-mark 0x1000/0xf000\n", 0xf000),
    ] {
        let input = base.replace("{}", rule);
        let observation = observe_android_xtables_fwmarks(
            input.as_bytes(),
            input.as_bytes(),
            AndroidNetdSourceProfile::AospNetd20250324,
            candidate(),
        )
        .unwrap();
        assert!(
            observation.legacy_mark_uses().contains(
                &FwmarkUseRecord::new(
                    FwmarkEvidenceSource::LegacyXtables,
                    FwmarkPlane::Packet,
                    FwmarkUseOperation::MaskedWrite,
                    mask,
                )
                .unwrap()
            )
        );
    }
}

#[test]
fn no_op_mutations_and_zero_transfer_planes_emit_no_mark_use() {
    let no_op = "*mangle\n:OUTPUT ACCEPT [0:0]\n-A OUTPUT -j MARK --and-mark 0xffffffff\nCOMMIT\n";
    let observation = observe_android_xtables_fwmarks(
        no_op.as_bytes(),
        no_op.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    assert!(observation.legacy_mark_uses().is_empty());

    let zero_nfmask = "*mangle\n:OUTPUT ACCEPT [0:0]\n-A OUTPUT -j CONNMARK --save-mark --nfmask 0 --ctmask 0xffff\nCOMMIT\n";
    let observation = observe_android_xtables_fwmarks(
        zero_nfmask.as_bytes(),
        zero_nfmask.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    assert_eq!(observation.transfer_mark_uses().len(), 1);
    assert_eq!(
        observation.transfer_mark_uses()[0],
        FwmarkUseRecord::new(
            FwmarkEvidenceSource::ConnmarkAndSocketTransfers,
            FwmarkPlane::Conntrack,
            FwmarkUseOperation::TransferWrite,
            0xffff,
        )
        .unwrap()
    );

    let zero_ctmask =
        zero_nfmask.replace("--nfmask 0 --ctmask 0xffff", "--nfmask 0xffff --ctmask 0");
    let observation = observe_android_xtables_fwmarks(
        zero_ctmask.as_bytes(),
        zero_ctmask.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    assert_eq!(observation.transfer_mark_uses().len(), 1);
    assert_eq!(
        observation.transfer_mark_uses()[0].plane(),
        FwmarkPlane::Packet
    );
    assert_eq!(
        observation.transfer_mark_uses()[0].operation(),
        FwmarkUseOperation::TransferRead
    );
}

#[test]
fn duplicate_targets_and_unknown_mark_extensions_fail_closed() {
    let base = "*mangle\n:OUTPUT ACCEPT [0:0]\n{}COMMIT\n";
    for rule in [
        "-A OUTPUT -j MARK --set-mark 1 -j ACCEPT\n",
        "-A OUTPUT -j MARK --set-mark 1 --set-xmark 2/2\n",
        "-A OUTPUT -j MARK --set-mark 1 --vendor-mark-mode opaque\n",
        "-A OUTPUT -j ACCEPT --set-mark 1\n",
        "-A OUTPUT -j MARK --set-mark 1 --nfmask 1\n",
    ] {
        let input = base.replace("{}", rule);
        assert_eq!(
            observe_android_xtables_fwmarks(
                input.as_bytes(),
                input.as_bytes(),
                AndroidNetdSourceProfile::AospNetd20250324,
                candidate(),
            )
            .unwrap_err()
            .kind(),
            AndroidXtablesFwmarkObservationErrorKind::UnknownMarkSemantics
        );
    }
}

#[test]
fn malformed_option_errors_retain_the_actual_family_and_line() {
    let ipv4 = "*mangle\n:OUTPUT ACCEPT [0:0]\nCOMMIT\n";
    let ipv6 = "*mangle\n:OUTPUT ACCEPT [0:0]\n-A OUTPUT -j\nCOMMIT\n";
    let error = observe_android_xtables_fwmarks(
        ipv4.as_bytes(),
        ipv6.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap_err();
    assert_eq!(error.family(), NetworkAddressFamily::Ipv6);
    assert_eq!(error.line(), Some(3));
    assert_eq!(
        error.kind(),
        AndroidXtablesFwmarkObservationErrorKind::UnknownMarkSemantics
    );
}

#[test]
fn canonical_snapshot_digest_detects_semantic_ab_drift() {
    let ipv4 = fixture(NetworkAddressFamily::Ipv4, "");
    let ipv6 = fixture(NetworkAddressFamily::Ipv6, "");
    let first = observe_android_xtables_fwmarks(
        ipv4.as_bytes(),
        ipv6.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    let changed_ipv6 = ipv6.replace("-o wlan0", "-o rmnet_data0");
    let second = observe_android_xtables_fwmarks(
        ipv4.as_bytes(),
        changed_ipv6.as_bytes(),
        AndroidNetdSourceProfile::AospNetd20250324,
        candidate(),
    )
    .unwrap();
    assert_ne!(first.digest(), second.digest());
}
