use super::*;

#[test]
fn projection_selects_one_mangle_table_and_ignores_other_tables_opaquely() {
    let input = br#"# Generated by iptables-save v1.8.11
*raw
:PREROUTING ACCEPT [0:0]
-A PREROUTING --opaque "unterminated syntax is irrelevant here
COMMIT
*mangle
:PREROUTING ACCEPT [12:345]
:OUTPUT ACCEPT [7:89]
:VENDOR_CHAIN - [1:2]
:FLX4SP - [3:4]
:FLX4SO - [5:6]
:FLX4P0000000007 - [9:10]
:FLX4O0000000007 - [11:12]
-A PREROUTING -m vendor_unknown --opaque "value with spaces" -j VENDOR_CHAIN
-A FLX4SP -i lo -m mark --mark 0x200000/0x600000 -j FLX4P0000000007
-A FLX4SO -m mark --mark 0x0/0x600000 -j FLX4O0000000007
-A PREROUTING -j FLX4SP
-A OUTPUT -j FLX4SO
COMMIT
*filter
:INPUT ACCEPT [0:0]
COMMIT
# Completed on a test clock
"#;
    let projection = project_xtables_save(input, XtablesRestoreFamily::Ipv4)
        .expect("bounded owned projection from full save document");

    assert_eq!(projection.family(), XtablesRestoreFamily::Ipv4);
    assert!(!projection.is_empty());
    assert_eq!(
        rules(&projection, "FLX4SP"),
        ["-A FLX4SP -i lo -m mark --mark 0x200000/0x600000 -j FLX4P0000000007"]
    );
    assert_eq!(
        rules(&projection, "FLX4SO"),
        ["-A FLX4SO -m mark --mark 0x0/0x600000 -j FLX4O0000000007"]
    );
    assert_eq!(projection.native_references().len(), 2);
    let prerouting = reference(&projection, "PREROUTING");
    assert_eq!(prerouting.ordinal().get(), 2);
    assert_eq!(prerouting.target_chains()[0].as_ref(), "FLX4SP");
    let output = reference(&projection, "OUTPUT");
    assert_eq!(output.ordinal().get(), 1);
    assert_eq!(output.target_chains()[0].as_ref(), "FLX4SO");
}

#[test]
fn missing_or_duplicate_mangle_tables_are_typed() {
    let missing = project_xtables_save(
        b"*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n",
        XtablesRestoreFamily::Ipv4,
    )
    .expect_err("full save without mangle must remain distinguishable");
    assert_eq!(
        missing.kind(),
        XtablesSaveProjectionErrorKind::MissingMangleTable
    );

    let duplicate = project_xtables_save(
        b"*mangle\nCOMMIT\n*filter\nCOMMIT\n*mangle\nCOMMIT\n",
        XtablesRestoreFamily::Ipv4,
    )
    .expect_err("duplicate mangle snapshot must fail");
    assert_eq!(
        duplicate.kind(),
        XtablesSaveProjectionErrorKind::DuplicateMangleTable
    );
}

#[test]
fn owned_state_outside_mangle_is_rejected() {
    let input = b"*filter\n:FLX4O0000000007 - [0:0]\nCOMMIT\n*mangle\nCOMMIT\n";
    let error = project_xtables_save(input, XtablesRestoreFamily::Ipv4)
        .expect_err("Flux-owned state outside mangle must fail closed");
    assert_eq!(
        error.kind(),
        XtablesSaveProjectionErrorKind::OwnedStateOutsideMangle
    );
}

#[test]
fn counter_changes_do_not_change_projection_identity() {
    let first = project_xtables_save(
        b"*mangle\n:FLX4SP - [1:2]\n-A PREROUTING -j FLX4SP\nCOMMIT\n",
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    let second = project_xtables_save(
        b"*mangle\n:FLX4SP - [999:888]\n-A PREROUTING -j FLX4SP\nCOMMIT\n",
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    assert_eq!(first, second);
    assert_eq!(first.digest(), second.digest());
}

#[test]
fn chain_creation_and_emission_order_is_canonical() {
    let first = project_xtables_save(
        br#"*mangle
:FLX4SP - [0:0]
:FLX4SO - [0:0]
:FLX4P0000000007 - [0:0]
:FLX4O0000000007 - [0:0]
-A FLX4SP -j FLX4P0000000007
-A FLX4SO -j FLX4O0000000007
-A PREROUTING -j FLX4SP
-A OUTPUT -j FLX4SO
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    let reordered = project_xtables_save(
        br#"*mangle
:FLX4O0000000007 - [0:0]
:FLX4P0000000007 - [0:0]
:FLX4SO - [0:0]
:FLX4SP - [0:0]
-A OUTPUT -j FLX4SO
-A FLX4SO -j FLX4O0000000007
-A PREROUTING -j FLX4SP
-A FLX4SP -j FLX4P0000000007
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();

    assert_eq!(first, reordered);
    assert_eq!(first.digest(), reordered.digest());
}

#[test]
fn same_chain_rule_order_and_duplicates_remain_material() {
    let first = project_xtables_save(
        br#"*mangle
:FLX4SP - [0:0]
:FLX4P0000000007 - [0:0]
:FLX4F0000000007 - [0:0]
-A FLX4SP -j FLX4P0000000007
-A FLX4SP -j FLX4F0000000007
-A PREROUTING -j FLX4SP
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    let reordered = project_xtables_save(
        br#"*mangle
:FLX4SP - [0:0]
:FLX4P0000000007 - [0:0]
:FLX4F0000000007 - [0:0]
-A FLX4SP -j FLX4F0000000007
-A FLX4SP -j FLX4P0000000007
-A PREROUTING -j FLX4SP
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    let duplicated = project_xtables_save(
        br#"*mangle
:FLX4SP - [0:0]
:FLX4P0000000007 - [0:0]
:FLX4F0000000007 - [0:0]
-A FLX4SP -j FLX4P0000000007
-A FLX4SP -j FLX4F0000000007
-A FLX4SP -j FLX4F0000000007
-A PREROUTING -j FLX4SP
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();

    assert_ne!(first, reordered);
    assert_ne!(first, duplicated);
    assert_eq!(rules(&duplicated, "FLX4SP").len(), 3);
}

#[test]
fn absolute_hook_ordinal_detects_displacement_by_opaque_rules() {
    let top = project_xtables_save(
        br#"*mangle
:PREROUTING ACCEPT [0:0]
:VENDOR - [0:0]
:FLX4SP - [0:0]
-A PREROUTING -j FLX4SP
-A PREROUTING -m vendor --opaque "ignored syntax" -j VENDOR
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    let displaced = project_xtables_save(
        br#"*mangle
:PREROUTING ACCEPT [0:0]
:VENDOR - [0:0]
:FLX4SP - [0:0]
-A PREROUTING -m vendor --opaque "ignored syntax" -j VENDOR
-A PREROUTING -j FLX4SP
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();

    assert_eq!(reference(&top, "PREROUTING").ordinal().get(), 1);
    assert_eq!(reference(&displaced, "PREROUTING").ordinal().get(), 2);
    assert_ne!(top, displaced);
}

#[test]
fn unrelated_state_projects_exact_clean_absence() {
    let projection = project_xtables_save(
        br#"*raw
:PREROUTING ACCEPT [0:0]
COMMIT
*mangle
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -m unknown --value "opaque text" -j ACCEPT
COMMIT
*filter
:INPUT ACCEPT [0:0]
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    assert!(projection.is_empty());
    assert!(projection.native_references().is_empty());
}

#[test]
fn duplicate_and_non_closed_native_state_fails_closed() {
    for (input, kind) in [
        (
            b"*mangle\n:FLX4SP - [0:0]\n:FLX4SP - [0:0]\nCOMMIT\n".as_slice(),
            XtablesSaveProjectionErrorKind::DuplicateNativeChain,
        ),
        (
            b"*mangle\n-A FLX4SP -j ACCEPT\nCOMMIT\n".as_slice(),
            XtablesSaveProjectionErrorKind::UndeclaredNativeSource,
        ),
        (
            b"*mangle\n:FLX4SP - [0:0]\n-A FLX4SP -j FLX4P0000000007\nCOMMIT\n".as_slice(),
            XtablesSaveProjectionErrorKind::DanglingNativeTarget,
        ),
    ] {
        let error = project_xtables_save(input, XtablesRestoreFamily::Ipv4)
            .expect_err("non-closed native save state must fail");
        assert_eq!(error.kind(), kind);
    }
}

#[test]
fn owned_chain_replacement_accepts_only_declared_native_jump_targets() {
    let projection = project_xtables_save(
        br#"*mangle
:FLX4A0000000007 - [0:0]
:FLX4C0000000007 - [0:0]
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    let declared = replacement_artifact(
        br#"*mangle
-F FLX4C0000000007
-A FLX4C0000000007 -m mark --mark 0x200000/0x600000 -j FLX4A0000000007
COMMIT
"#,
    );

    let replaced = projection
        .with_owned_chain_replacement(&declared)
        .expect("replacement may jump to an already-declared owned chain");
    assert_eq!(
        rules(&replaced, "FLX4C0000000007"),
        ["-A FLX4C0000000007 -m mark --mark 0x200000/0x600000 -j FLX4A0000000007"]
    );

    let dangling = replacement_artifact(
        br#"*mangle
-F FLX4C0000000007
-A FLX4C0000000007 -j FLX4A0000000008
COMMIT
"#,
    );
    assert_eq!(
        projection
            .with_owned_chain_replacement(&dangling)
            .expect_err("replacement must reject an undeclared owned target")
            .kind(),
        XtablesSaveProjectionErrorKind::ExpectedReplacementMismatch
    );
}

#[test]
fn cross_family_or_malformed_native_state_fails_closed() {
    for input in [
        b"*mangle\n:FLX6SP - [0:0]\nCOMMIT\n".as_slice(),
        b"*mangle\n:FLX4SX - [0:0]\nCOMMIT\n".as_slice(),
        b"*mangle\n:FLX4SP ACCEPT [0:0]\nCOMMIT\n".as_slice(),
        b"*mangle\n:FLX4SP - [bad:0]\nCOMMIT\n".as_slice(),
        b"*mangle\n:FLX4SP - [0:0]\n:FLX6P0000000007 - [0:0]\n-A FLX4SP -j FLX6P0000000007\nCOMMIT\n"
            .as_slice(),
    ] {
        assert!(project_xtables_save(input, XtablesRestoreFamily::Ipv4).is_err());
    }
}

#[test]
fn expected_active_state_normalizes_insert_hooks_to_live_append_form() {
    let private = apply_artifact(
        br#"*mangle
:FLX4P0000000007 - [0:0]
:FLX4O0000000007 - [0:0]
-A FLX4P0000000007 -j ACCEPT
-A FLX4O0000000007 -j ACCEPT
COMMIT
"#,
    );
    let stable = apply_artifact(
        br#"*mangle
:FLX4SP - [0:0]
:FLX4SO - [0:0]
-A FLX4SP -i lo -m mark --mark 0x200000/0x600000 -j FLX4P0000000007
-A FLX4SO -m mark --mark 0x0/0x600000 -j FLX4O0000000007
-I PREROUTING -j FLX4SP
-I OUTPUT -j FLX4SO
COMMIT
"#,
    );
    let active = XtablesExpectedState::from_apply_artifacts(
        XtablesRestoreFamily::Ipv4,
        XtablesExpectedStatePhase::Active,
        [&private, &stable],
    )
    .unwrap();
    let output_detached = XtablesExpectedState::from_apply_artifacts(
        XtablesRestoreFamily::Ipv4,
        XtablesExpectedStatePhase::OutputDetached,
        [&private, &stable],
    )
    .unwrap();

    let observed_active = project_xtables_save(
        br#"*mangle
:FLX4SO - [8:9]
:FLX4O0000000007 - [1:2]
:FLX4SP - [3:4]
:FLX4P0000000007 - [5:6]
-A PREROUTING -j FLX4SP
-A OUTPUT -j FLX4SO
-A FLX4SO -m mark --mark 0x0/0x600000 -j FLX4O0000000007
-A FLX4SP -i lo -m mark --mark 0x200000/0x600000 -j FLX4P0000000007
-A FLX4O0000000007 -j ACCEPT
-A FLX4P0000000007 -j ACCEPT
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();
    let observed_detached = project_xtables_save(
        br#"*mangle
:FLX4SO - [0:0]
:FLX4O0000000007 - [0:0]
:FLX4SP - [0:0]
:FLX4P0000000007 - [0:0]
-A PREROUTING -j FLX4SP
-A FLX4SO -m mark --mark 0x0/0x600000 -j FLX4O0000000007
-A FLX4SP -i lo -m mark --mark 0x200000/0x600000 -j FLX4P0000000007
-A FLX4O0000000007 -j ACCEPT
-A FLX4P0000000007 -j ACCEPT
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .unwrap();

    assert_eq!(active.phase(), XtablesExpectedStatePhase::Active);
    assert!(active.is_satisfied_by(&observed_active));
    assert!(!active.is_satisfied_by(&observed_detached));
    assert!(output_detached.is_satisfied_by(&observed_detached));
    assert!(
        active
            .projection()
            .native_references()
            .iter()
            .all(|reference| reference.rule().as_str().starts_with("-A "))
    );
}

#[test]
fn malformed_save_framing_and_quotes_are_rejected() {
    for (input, kind) in [
        (
            b"*mangle\n-A PREROUTING -m comment --comment \"unterminated -j ACCEPT\nCOMMIT\n"
                .as_slice(),
            XtablesSaveProjectionErrorKind::InvalidQuotedToken,
        ),
        (
            b"*mangle\n:PREROUTING ACCEPT [0:0]\n".as_slice(),
            XtablesSaveProjectionErrorKind::MissingCommit,
        ),
        (
            b"*mangle\nCOMMIT\ntrailing\n".as_slice(),
            XtablesSaveProjectionErrorKind::ContentAfterCommit,
        ),
        (
            b"*filter\nCOMMIT\n*mangle\nCOMMIT\n*nat\nunterminated\n".as_slice(),
            XtablesSaveProjectionErrorKind::MissingCommit,
        ),
    ] {
        let error = project_xtables_save(input, XtablesRestoreFamily::Ipv4)
            .expect_err("malformed save output must fail");
        assert_eq!(error.kind(), kind);
    }
}

#[test]
fn invalid_owned_artifact_reports_the_original_save_line() {
    let error = project_xtables_save(
        br#"# header
*mangle
:FLX4SP - [0:0]
-A PREROUTING -j ACCEPT
-A FLX4SP --unsupported value -j ACCEPT
COMMIT
"#,
        XtablesRestoreFamily::Ipv4,
    )
    .expect_err("unsupported owned rule must fail closed");
    assert_eq!(
        error.kind(),
        XtablesSaveProjectionErrorKind::InvalidOwnedArtifact
    );
    assert_eq!(error.line(), Some(5));
}

#[test]
fn live_tproxy_default_on_ip_is_normalized_but_nondefault_addresses_fail_closed() {
    for (family, chain, default) in [
        (XtablesRestoreFamily::Ipv4, "FLX4P0000000007", "0.0.0.0"),
        (XtablesRestoreFamily::Ipv6, "FLX6P0000000007", "::"),
    ] {
        let canonical = format!(
            "*mangle\n:{chain} - [0:0]\n-A {chain} -p tcp -j TPROXY --on-port 1536 --tproxy-mark 0x200000/0x600000\nCOMMIT\n"
        );
        let live = format!(
            "*mangle\n:{chain} - [0:0]\n-A {chain} -p tcp -j TPROXY --on-port 1536 --on-ip {default} --tproxy-mark 0x200000/0x600000\nCOMMIT\n"
        );
        assert_eq!(
            project_xtables_save(live.as_bytes(), family).unwrap(),
            project_xtables_save(canonical.as_bytes(), family).unwrap()
        );

        let nondefault = format!(
            "*mangle\n:{chain} - [0:0]\n-A {chain} -p tcp -j TPROXY --on-port 1536 --on-ip 192.0.2.1 --tproxy-mark 0x200000/0x600000\nCOMMIT\n"
        );
        assert_eq!(
            project_xtables_save(nondefault.as_bytes(), family)
                .unwrap_err()
                .kind(),
            XtablesSaveProjectionErrorKind::InvalidOwnedArtifact
        );
    }
}

#[test]
fn save_output_line_count_is_bounded_across_all_tables() {
    let mut exact = "#\n".repeat(MAX_XTABLES_RESTORE_LINES - 4);
    exact.push_str("*filter\nCOMMIT\n*mangle\nCOMMIT\n");
    let projection = project_xtables_save(exact.as_bytes(), XtablesRestoreFamily::Ipv4)
        .expect("maximum full-document line count remains admitted");
    assert!(projection.is_empty());

    let mut oversized = String::from("#\n");
    oversized.push_str(&exact);
    let error = project_xtables_save(oversized.as_bytes(), XtablesRestoreFamily::Ipv4)
        .expect_err("save output above the line limit must fail closed");
    assert_eq!(error.kind(), XtablesSaveProjectionErrorKind::LimitExceeded);
}

fn apply_artifact(bytes: &[u8]) -> XtablesRestoreArtifact {
    parse_xtables_restore(
        bytes,
        XtablesRestoreContext::new(XtablesRestoreAction::Apply, XtablesRestoreFamily::Ipv4),
    )
    .unwrap()
}

fn replacement_artifact(bytes: &[u8]) -> XtablesRestoreArtifact {
    parse_xtables_restore(
        bytes,
        XtablesRestoreContext::new(XtablesRestoreAction::Replace, XtablesRestoreFamily::Ipv4),
    )
    .unwrap()
}

fn rules<'a>(projection: &'a XtablesSaveProjection, chain: &str) -> Vec<&'a str> {
    projection
        .chain(chain)
        .expect("owned chain")
        .rules()
        .iter()
        .map(XtablesOwnedRule::as_str)
        .collect()
}

fn reference<'a>(
    projection: &'a XtablesSaveProjection,
    source: &str,
) -> &'a XtablesNativeReference {
    projection
        .native_references()
        .iter()
        .find(|reference| reference.source_chain() == source)
        .expect("native reference from source")
}
